package org.coepi.android.domain.symptomflow

enum class SymptomStep {
    COUGH_TYPE, COUGH_DESCRIPTION, BREATHLESSNESS_DESCRIPTION, FEVER_TEMPERATURE_TAKEN_TODAY,
    FEVER_TEMPERATURE_SPOT, FEVER_TEMPERATURE_SPOT_INPUT, FEVER_HIGHEST_TEMPERATURE,
    EARLIEST_SYMPTOM
}
